version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build_docs:
    executor: python/default
    steps:
      - checkout
      - python/install-deps
      - run:
          name: Build cheatsheets and docs
          command: make all
      - persist_to_workspace:
          root: docs/_build/html
          paths: .
      - store_artifacts:
          path: docs/_build/html/

workflows:
  main:
    jobs:
      - build_docs
